# Generated by Django 3.1.6 on 2021-03-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.CharField(default='', max_length=50)),
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Quantity', models.FloatField()),
                ('Price', models.FloatField()),
                ('Total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=500)),
                ('commenter', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
                ('Recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedAdmin',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedRating',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedSearch',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
                ('User', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RP', models.BinaryField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Buy_rate', models.FloatField()),
                ('Sell_rate', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Available', models.IntegerField(default=0)),
                ('Sell', models.IntegerField(default=0)),
            ],
        ),
    ]
