# Generated by Django 3.1.3 on 2020-11-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='id',
        ),
        migrations.AlterField(
            model_name='logs',
            name='Email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
