# Generated by Django 3.1.6 on 2021-03-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Crousal',
            field=models.BooleanField(default=False),
        ),
    ]
