# Generated by Django 3.1.3 on 2020-11-13 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0002_auto_20201113_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Time', models.TimeField(default=datetime.datetime(2020, 11, 13, 22, 31, 56, 165835))),
            ],
        ),
    ]
