# Generated by Django 3.1.3 on 2020-11-13 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Picture',
            field=models.ImageField(default='', upload_to='Shopping/static'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2020, 11, 14, 0, 25, 34, 475946)),
        ),
    ]
