# Generated by Django 3.1.3 on 2020-11-14 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0004_auto_20201114_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 16, 18, 34, 449551)),
        ),
    ]
