# Generated by Django 3.1.3 on 2020-11-14 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0005_auto_20201114_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 14, 16, 28, 14, 757698)),
        ),
    ]
