# Generated by Django 3.1.3 on 2020-11-15 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0008_auto_20201115_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 15, 18, 56, 24, 191167)),
        ),
    ]
