# Generated by Django 3.1.3 on 2020-11-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0009_auto_20201115_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Quantity', models.FloatField()),
                ('Price', models.FloatField()),
                ('Total', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 18, 23, 48, 17, 121435)),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
