# Generated by Django 3.1.3 on 2020-11-19 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0010_auto_20201118_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 19, 15, 30, 25, 490059)),
        ),
    ]
