# Generated by Django 3.1.3 on 2020-11-20 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0011_auto_20201119_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 20, 17, 37, 32, 686731)),
        ),
    ]
