# Generated by Django 3.1.3 on 2020-11-20 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0014_auto_20201120_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 20, 18, 0, 55, 605011)),
        ),
    ]
