# Generated by Django 3.1.3 on 2020-11-20 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0019_auto_20201120_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 20, 23, 50, 50, 581125)),
        ),
    ]
