# Generated by Django 3.1.3 on 2020-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0041_auto_20201121_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Time',
            field=models.DateTimeField(null=True),
        ),
    ]
