# Generated by Django 3.1.3 on 2020-11-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0043_auto_20201128_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Total', models.IntegerField()),
                ('Available', models.IntegerField()),
                ('Sell', models.IntegerField()),
            ],
        ),
    ]
