# Generated by Django 3.1.3 on 2020-11-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0045_auto_20201130_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Buy_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Sell_rate',
            field=models.FloatField(),
        ),
    ]
