# Generated by Django 3.1.3 on 2020-11-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0046_auto_20201130_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockQuantity',
        ),
    ]
