# Generated by Django 3.1.3 on 2021-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0047_delete_stockquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
