# Generated by Django 3.1.6 on 2021-02-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0048_comment_commenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('item', models.CharField(max_length=200)),
            ],
        ),
    ]
