# Generated by Django 3.1.6 on 2021-02-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0049_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='title',
            new_name='user',
        ),
    ]
