# Generated by Django 3.1.6 on 2021-02-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0050_auto_20210217_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedAdmin',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedRating',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedSearch',
            fields=[
                ('title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('Price', models.FloatField()),
                ('Time', models.DateTimeField(null=True)),
                ('Picture', models.ImageField(default='', upload_to='Shopping/static')),
                ('Quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
