# Generated by Django 3.1.6 on 2021-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0053_recommendedsearch_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendUserBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllItems', models.BinaryField(max_length=1000, null=True)),
            ],
        ),
    ]
