# Generated by Django 3.1.6 on 2021-02-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0054_recommenduserbuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommenduserbuy',
            old_name='AllItems',
            new_name='All_Items',
        ),
    ]
