# Generated by Django 3.1.6 on 2021-02-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0055_auto_20210219_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('All_Items', models.BinaryField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendUserBuy',
        ),
    ]
