# Generated by Django 3.1.6 on 2021-02-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0056_auto_20210219_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommenduser',
            old_name='All_Items',
            new_name='RP',
        ),
    ]
