# Generated by Django 3.1.6 on 2021-02-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0057_auto_20210219_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommenduser',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
