# Generated by Django 3.1.6 on 2021-02-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0058_recommenduser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommenduser',
            name='Name',
        ),
    ]
