# Generated by Django 3.1.6 on 2021-02-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0060_auto_20210221_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendedadmin',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendedrating',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recommendedrating',
            name='title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommendedsearch',
            name='Description',
            field=models.CharField(max_length=200),
        ),
    ]
