# Generated by Django 3.1.3 on 2020-11-20 12:37

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Receiver', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Zip', models.IntegerField()),
                ('Name_on_Card', models.CharField(max_length=50)),
                ('Credit_card_number', creditcards.models.CardNumberField(max_length=25)),
                ('Exp_Month', creditcards.models.CardExpiryField()),
                ('CVV', models.IntegerField()),
            ],
        ),
    ]
