# Generated by Django 3.1.3 on 2020-11-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckedOut',
            new_name='All_Bill',
        ),
    ]
