# Generated by Django 3.1.3 on 2020-11-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20201120_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_bill',
            name='Payment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
