# Generated by Django 3.1.3 on 2020-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_all_bill_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_bill',
            name='All_fields',
            field=models.CharField(default='', max_length=300),
        ),
    ]
