# Generated by Django 3.1.3 on 2020-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_all_bill_all_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_bill',
            name='Exp_Year',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Exp_Month',
            field=models.CharField(default='', max_length=50),
        ),
    ]
