# Generated by Django 3.1.3 on 2020-11-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20201120_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_bill',
            name='Amount',
            field=models.IntegerField(default=123),
        ),
    ]
