# Generated by Django 3.1.3 on 2020-11-20 18:43

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_all_bill_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_bill',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='All_fields',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Credit_card_number',
            field=creditcards.models.CardNumberField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Exp_Month',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Exp_Year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Name_on_Card',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Payment',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Receiver',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='User',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='all_bill',
            name='Zip',
            field=models.IntegerField(null=True),
        ),
    ]
