# Generated by Django 3.1.3 on 2020-11-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20201120_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_bill',
            name='CVV',
            field=models.IntegerField(null=True),
        ),
    ]
