# Generated by Django 3.1.3 on 2020-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_auto_20201120_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_bill',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
