# Generated by Django 3.1.3 on 2020-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0012_auto_20201121_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_bill',
            name='All_fields',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
