# Generated by Django 3.1.3 on 2020-11-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_auto_20201121_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_bill',
            name='All_fields',
            field=models.BinaryField(max_length=1000, null=True),
        ),
    ]
