# Generated by Django 3.1.3 on 2020-11-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_auto_20201122_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_bill',
            name='Amount',
            field=models.FloatField(null=True),
        ),
    ]
