# Generated by Django 3.1.3 on 2021-01-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_auto_20201130_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_Name', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
