# Generated by Django 3.1.3 on 2021-01-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_pendingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingorder',
            name='Bill_number',
            field=models.TextField(null=True),
        ),
    ]
