# Generated by Django 3.1.3 on 2021-01-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_pendingorder_bill_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_Name', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Bill_number', models.TextField(null=True)),
            ],
        ),
    ]
