# Generated by Django 3.1.3 on 2021-01-01 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatched',
            name='Shipped_Date',
            field=models.DateField(default=datetime.datetime(2021, 1, 2, 0, 18, 20, 352881)),
        ),
    ]
